# Generated by Django 5.2.14 on 2026-05-06 01:02

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
                ("cnpj", models.CharField(max_length=18, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(max_length=20)),
                ("category", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("logo", models.ImageField(blank=True, null=True, upload_to="companies/logos/")),
                ("banner", models.ImageField(blank=True, null=True, upload_to="companies/banners/")),
                ("cep", models.CharField(max_length=10)),
                ("address", models.CharField(max_length=255)),
                ("number", models.CharField(max_length=20)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("advantage1", models.CharField(blank=True, max_length=255)),
                ("advantage2", models.CharField(blank=True, max_length=255)),
                ("advantage3", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "db_table": "companies",
            },
        ),
    ]
