# Generated by Django 5.2.14 on 2026-05-12 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_businesshour"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businesshour",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="business_hours", to="companies.company"
            ),
        ),
    ]
