# Generated by Django 5.2.14 on 2026-05-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0003_alter_businesshour_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businesshour",
            name="week_day",
            field=models.CharField(
                choices=[
                    ("monday", "Segunda-feira"),
                    ("tuesday", "Terça-feira"),
                    ("wednesday", "Quarta-feira"),
                    ("thursday", "Quinta-feira"),
                    ("friday", "Sexta-feira"),
                    ("saturday", "Sábado"),
                    ("sunday", "Domingo"),
                ],
                max_length=20,
            ),
        ),
    ]
