# Generated by Django 5.2.14 on 2026-05-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0004_alter_businesshour_week_day"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businesshour",
            name="week_day",
            field=models.CharField(
                choices=[
                    ("monday", "Monday"),
                    ("tuesday", "Tuesday"),
                    ("wednesday", "Wednesday"),
                    ("thursday", "Thursday"),
                    ("friday", "Friday"),
                    ("saturday", "Saturday"),
                    ("sunday", "Sunday"),
                ],
                max_length=20,
            ),
        ),
    ]
