# Generated by Django 5.2.14 on 2026-05-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0005_alter_businesshour_week_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="rating",
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name="businesshour",
            name="week_day",
            field=models.CharField(
                choices=[
                    ("monday", "Segunda-feira"),
                    ("tuesday", "Terça-feira"),
                    ("wednesday", "Quarta-feira"),
                    ("thursday", "Quinta-feira"),
                    ("friday", "Sexta-feira"),
                    ("saturday", "Sábado"),
                    ("sunday", "Domingo"),
                ],
                max_length=20,
            ),
        ),
    ]
