# Generated by Django 5.2.14 on 2026-05-08 23:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Professional",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
                ("full_name", models.CharField(max_length=255)),
                ("position", models.CharField(max_length=150)),
                ("rating", models.DecimalField(decimal_places=1, default=5.0, max_digits=3)),
                ("avatar", models.ImageField(blank=True, null=True, upload_to="professionals/avatars/")),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="%(class)ss", to="companies.company"
                    ),
                ),
            ],
            options={
                "db_table": "professionals",
                "ordering": ["full_name"],
            },
        ),
    ]
