# Generated by Django 5.2.14 on 2026-05-08 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("professionals", "0001_initial"),
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="professional",
            name="services",
            field=models.ManyToManyField(blank=True, related_name="professionals", to="services.service"),
        ),
    ]
