# Generated by Django 5.2.14 on 2026-05-06 01:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "code",
                    models.CharField(
                        choices=[("trial", "Trial"), ("start", "Start"), ("pro", "Pro"), ("business", "Business")],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("monthly_price", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("max_professionals", models.IntegerField(default=1)),
                ("max_services", models.IntegerField(default=3)),
                ("max_appointments", models.IntegerField(default=30)),
                ("allow_chat", models.BooleanField(default=False)),
                ("allow_reports", models.BooleanField(default=False)),
                ("allow_automation", models.BooleanField(default=False)),
                ("allow_full_dashboard", models.BooleanField(default=False)),
                ("trial_days", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "subscription_plans",
            },
        ),
        migrations.CreateModel(
            name="SubscriptionUsage",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("trial", "Trial"),
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="trial",
                        max_length=20,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("current_professionals", models.IntegerField(default=0)),
                ("current_services", models.IntegerField(default=0)),
                ("current_appointments", models.IntegerField(default=0)),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription_usage",
                        to="companies.company",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="companies_usage",
                        to="subscriptions.subscriptionplan",
                    ),
                ),
            ],
            options={
                "db_table": "subscription_usage",
            },
        ),
    ]
