# Generated by Django 5.2.14 on 2026-05-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0002_alter_subscriptionplan_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplan",
            name="badge_variant",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="ribbon_text",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="ribbon_variant",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
