# Generated by Django 5.2.14 on 2026-05-17 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0003_subscriptionplan_badge_variant_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscriptionplan",
            name="badge",
        ),
        migrations.RemoveField(
            model_name="subscriptionplan",
            name="badge_variant",
        ),
        migrations.RemoveField(
            model_name="subscriptionplan",
            name="icon",
        ),
        migrations.RemoveField(
            model_name="subscriptionplan",
            name="ribbon_text",
        ),
        migrations.RemoveField(
            model_name="subscriptionplan",
            name="ribbon_variant",
        ),
    ]
