# Generated by Django 5.2.14 on 2026-05-12 20:04

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0006_company_rating_alter_businesshour_week_day"),
        ("professionals", "0002_initial"),
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("confirmed", "Confirmado"),
                            ("cancelled", "Cancelado"),
                            ("completed", "Concluído"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("user_name", models.CharField(max_length=255)),
                ("user_phone", models.CharField(max_length=20)),
                ("user_email", models.EmailField(blank=True, max_length=254)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="%(class)ss", to="companies.company"
                    ),
                ),
                (
                    "professional",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="professionals.professional",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="appointments", to="services.service"
                    ),
                ),
            ],
            options={
                "db_table": "appointments",
                "ordering": ["date", "time"],
                "unique_together": {("professional", "date", "time")},
            },
        ),
    ]
