# Generated by Django 5.2.14 on 2026-05-18 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0001_initial"),
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointments",
                to="clients.client",
            ),
        ),
    ]
