# Generated by Django 5.2.14 on 2026-05-18 15:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
        ("companies", "0006_company_rating_alter_businesshour_week_day"),
        ("notifications", "0001_initial"),
        ("professionals", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "recipient_type",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("professional", "Professional"),
                            ("client", "Client"),
                            ("staff", "Staff"),
                        ],
                        max_length=20,
                    ),
                ),
                ("allow_in_app", models.BooleanField(default=True)),
                ("allow_whatsapp", models.BooleanField(default=True)),
                ("booking_created", models.BooleanField(default=True)),
                ("booking_confirmed", models.BooleanField(default=True)),
                ("booking_cancelled", models.BooleanField(default=True)),
                ("booking_reminder", models.BooleanField(default=True)),
                ("subscription_expiring", models.BooleanField(default=True)),
                ("system_message", models.BooleanField(default=True)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to="clients.client",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="%(class)ss", to="companies.company"
                    ),
                ),
                (
                    "professional",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to="professionals.professional",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notification_preferences",
            },
        ),
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "event_key",
                    models.CharField(
                        choices=[
                            ("booking_created", "Booking Created"),
                            ("booking_confirmed", "Booking Confirmed"),
                            ("booking_cancelled", "Booking Cancelled"),
                            ("booking_reminder", "Booking Reminder"),
                            ("subscription_expiring", "Subscription Expiring"),
                            ("system_message", "System Message"),
                        ],
                        max_length=50,
                    ),
                ),
                ("channel", models.CharField(choices=[("in_app", "In App"), ("whatsapp", "WhatsApp")], max_length=20)),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("professional", "Professional"),
                            ("client", "Client"),
                            ("staff", "Staff"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title_template", models.CharField(blank=True, max_length=255)),
                ("body_template", models.TextField()),
                ("placeholders", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_templates",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "db_table": "notification_templates",
                "ordering": ["event_key", "channel", "audience"],
            },
        ),
    ]
