# Generated by Django 5.2.14 on 2026-05-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_notificationpreference_notificationtemplate"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationpreference",
            name="allow_email",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="channel",
            field=models.CharField(
                choices=[("in_app", "In App"), ("whatsapp", "WhatsApp"), ("email", "Email")], max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="notificationtemplate",
            name="channel",
            field=models.CharField(
                choices=[("in_app", "In App"), ("whatsapp", "WhatsApp"), ("email", "Email")], max_length=20
            ),
        ),
    ]
